apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: micro-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: micro-api
    spec:
      containers:
        - name: api
          env:
          - name: MICRO_ENABLE_STATS
            value: "true"
          command: [
            "/micro",
            "api"
          ]
          image: microhq/micro:kubernetes
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: api-port
