apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: micro-bot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: micro-bot
    spec:
      containers:
        - name: bot
          command: [
            "/micro",
            "bot",
            "--inputs=slack",
            "--slack_token=YOUR_SLACK_TOKEN"
          ]
          image: microhq/micro:bot
          imagePullPolicy: Always
