apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: micro-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: micro-proxy
    spec:
      containers:
        - name: proxy
          env:
          - name: MICRO_ENABLE_STATS
            value: "true"
          command: [
            "/micro",
            "proxy"
          ]
          image: microhq/micro:kubernetes
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
            name: proxy-port
