apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: greeter-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: greeter-web
    spec:
      containers:
        - name: greeter-web
          command: [
		"/greeter-web"
	  ]
          image: microhq/greeter-web:kubernetes
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: web-port
